sudo: false
language: python
python:
  - "2.7"
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
matrix:
  fast_finish: true
  include:
    - python: 3.4
      env: TOXENV=py34-django11
    - python: 3.4
      env: TOXENV=py34-django20
    - python: 3.4
      env: TOXENV=py34-django21
    - python: 3.5
      env: TOXENV=py35-django11
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.5
      env: TOXENV=py35-django21
    - python: 3.6
      env: TOXENV=py36-django11
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.6
      env: TOXENV=flake8
cache:
  directories:
    - $HOME/.pip_cache
install:
  - "travis_retry pip install setuptools --upgrade"
  - "pip install tox coveralls"
script:
  - tox -e $TOXENV
after_success:
  - coveralls -v

